## Important concepts to keep in mind

* Basic Data types
    * int, floats, booleans, strings
* Data Structures
    * lists
    * sets
    * dictionaries
    * tuples
* Functions
    * return
* Libraries 
    * numpy 
 

## Python basics

Answer the questions or complete the tasks outlined in bold below, use the specific method described if applicable.

Q1. **What is 7 to the power of 4?**

In [1]:
7**4

2401

Q2. **Split this string into a list.**

In [2]:
s = "Hi there Sam!"

In [9]:
s.split()

['Hi', 'there', 'Sam!']

Q3.**Given the variables *planet* and *diameter*, use .format() to print the following string** 

     The diameter of Earth is 12742 kilometers.
     
String formating is just a way to inject a variable into a string without typing/hard-coding the variable into the string. 

In [7]:
planet = "Earth"
diameter = 12742

In [8]:
print('The diameter of {} is {} kilometers'.format(planet, diameter))

The diameter of Earth is 12742 kilometers


Q4.**Print the same statement as above using the given planet and diameter variables but instead of .format(), use an f' string (formatted string literals).**

    Example: print(f'The date today is {}.') where date is a string or a datetime, which has been defined

In [18]:
print(f'The diameter of {planet} is {diameter} kilometers')

The diameter of Earth is 12742 kilometers


Q5.**Use either .format() or a formatted string literal to print out your name and place of residence. I have given an example below with myself.**

In [21]:
name = 'Violeta'
city = 'Amsterdam'
country = 'the Netherlands'
print(f'{name} lives in {city}, which is a city in {country}')

Violeta lives in Amsterdam, which is a city in the Netherlands


Q6.**Nested lists are lists of lists. We can index them the same way we would with a normal list. Remember that lists can store data from various types but are not always memory or operation efficient. They can ne modified (in other words, they are mutable) and they can be sorted (dictionaries cannot be sorted). 
    Your task is:**
    
    Given this nested list, use indexing to grab the word "hello"

In [10]:
lst = [1,2,[3,4],[5,[100,200,['hello']],23,11],1,7]

In [15]:
lst[3][1][2][0]

'hello'

Q7.**You are given the below 3 lists. Concatenate them together, so that they form one list and then remove the last element of the newly formed list.**

    Note: .append() is a useful command to add to a list but it allows you to add one elements of a time to a list 

In [111]:
lst1 = [1, 9, 21]
lst2 = [[1, [2], [3,4]]]
lst3 = [5, 6, [5, 6]]

In [112]:
new_list = lst1 + lst2 + lst3
new_list.pop()
print(new_list)

[1, 9, 21, [1, [2], [3, 4]], 5, 6]


Q8.**Similarly to lists, dictionaries are another useful data type, which stores data as a key:value pairs but are not ordered. Dictionaries can contain data from different data types but unlike lists, they are unordered and cannot be sorted.** 

    Given this nested dictionary grab the word "hello". Be prepared, this will be annoying :) 

In [47]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [57]:
d['k1'][3]['tricky'][3]['target'][3]

'hello'

Q9.**Let's practice dictionaries in another exercise. Given the dictionary below, grab the letter 'c' and make it uppercase.**

In [58]:
d = {'key1': ['a', 'b', 'c']}

In [60]:
d['key1'][2].upper()

'C'

Q10.**We will learn about complex function in later weeks but for now, we can build something simple. A function in Python has the following structure:**
    
    def functions_name(arguments):
    do something
    return something
    
    Create a function that grabs the website domain from a string in the form user@domain.com. So for example, passing "user@domain.com" would return: domain.com

In [61]:
def domain_get(s):
    return s.split('@')[1]

In [62]:
domain_get('user@domain.com')

'domain.com'

Q10. **Create a basic function that returns True if the word 'dog' is contained in the input string. Don't worry about edge cases like a punctuation being attached to the word dog, but do account for capitalization.**

In [65]:
def find_dog(s):
    return 'dog' in s.lower().split()

In [28]:
find_dog('Is there a dog here?')

True

# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

We will only learn the basics of NumPy, to get started we need to install it!

#### Install numpy (or similarly, any other package)

In [69]:
!pip3 install numpy

#### Import NumPy as np

In [66]:
import numpy as np

#### Create an array of 10 zeros 

In [71]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [72]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [74]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [79]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [80]:
np.arange(10, 51, step=2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [81]:
np.arange(0, 9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Use NumPy to generate a random number between 0 and 1

In [89]:
np.random.rand()

0.3598091649627112

#### Create an array of 20 linearly spaced points between 0 and 1:

In [93]:
np.linspace(0,1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [94]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [39]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [95]:
mat[2:, 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [96]:
# get the last element of the second row
mat[1, -1]

10

In [31]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [102]:
mat[-1, :]

array([21, 22, 23, 24, 25])

In [32]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [103]:
mat[-2:, :]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Some more exercises

#### Get the sum of all the values in mat

In [105]:
np.sum(mat)

325

#### Get the standard deviation of the values in mat

In [109]:
np.std(mat) # == mat.std()

7.211102550927978

#### Get the sum of all the columns in mat

In [107]:
sum(mat)

array([55, 60, 65, 70, 75])